### ISSUE TITLE
Add locations of Islamic mosques on you git.io page. It would help me immensely. Thanks. :)

### ISSUE THREAD

**Issue by iluv3O3** [prakashmurthy/prakashmurthy.github.io#2]
![image](https://cloud.githubusercontent.com/assets/15055490/10413561/400e68f0-6f6b-11e5-9257-766e124af7b2.png)

**Comment by prakashmurthy** [comment]
:-) 

Just because I oppose Anti-islam hate rallies, it does not make me a muslim in any way. Nor am I an Arab. 

Since you seem to be unaware of my background, here it is: I am from India, and the religion I loosely subscribe to is Hinduism. So if you want to racially abuse me, the terms you should use are "Curry Muncher",  "Raghead", etc. http://www.rsdb.org/race/indians has lot more you could choose from :-)

Personally, I think you are in a lot of internal pain, and in need of psychiatric help. Hope you take that bold step to help yourself instead of lashing out at the outside world. 

If you happen to be visiting Longmont any time soon, let me know. I would love to meet up with you and learn more about you.

Regards,
Prakash

**Comment by iluv3O3** [comment]
Prakash, thank you for the prompt reply. Sorry if my issue I put forward was not to your liking. Regards, James. Ruby on man.
